Sot 31: Write 3 chapter of Why and how zk snark works
sota-zk-lab/documents pull request #16
Opened 2023-12-20 11:08 UTC by Draply

- [ ] Did you check your grammar / reader proof your document using ChatGPT?
- [ ] Don't forget to squash commits into meaningful chunks before merging
- [ ] After merging this, please update your task status!

2023-12-23 09:20 UTC, sonntuet1997 requested changes

2023-12-23 09:20 UTC, sonntuet1997 commented on articles/why-and-how-zk-snark-works/1.Introduction.md
> +Zero-knowledge succinct non-interactive arguments of knowledge (zk-SNARKs) are a truly ingenious method of proving that something is true without revealing any other information.
Missing header

2023-12-23 09:21 UTC, sonntuet1997 commented on articles/why-and-how-zk-snark-works/2.The_Medium_of_a_Proof.md
> +![[Pasted image 20231214150151.png]]
Malfunction images

2023-12-23 09:21 UTC, sonntuet1997 commented on articles/why-and-how-zk-snark-works/2.The_Medium_of_a_Proof.md
> +**The Fundamental Theorem of Algebra** tells us that a degree d **polynomial** can have at most d solutions , and therefore at most d shared points.
Add ref

2023-12-23 09:22 UTC, sonntuet1997 commented on articles/why-and-how-zk-snark-works/2.The_Medium_of_a_Proof.md
> +In fact, out of all choices of *x* to evaluate, only at most 3 choices will have equal evaluations in those polynomials, and all others will differ.
3 choices ?

2023-12-23 09:23 UTC, sonntuet1997 commented on articles/why-and-how-zk-snark-works/2.The_Medium_of_a_Proof.md
> + Consider an integer range of *x* from 1 to $10^{77}$, the number of points where evaluations are different is *$10^{77}-d$*. Henceforth the probability that *x* accidentally “hits” any of the d shar
Malfunction math

2023-12-23 09:23 UTC, sonntuet1997 commented on articles/why-and-how-zk-snark-works/2.The_Medium_of_a_Proof.md
> +Let us consider **polynomials**, which can be visualized as a curve on a graph, shaped by mathematical equations:
Missing header

2023-12-23 09:24 UTC, sonntuet1997 commented on articles/why-and-how-zk-snark-works/3.Non_Interactive_Zero-Knowledge_of_a_Polynomial.md
> +## 3.1. **The Fundamental Theorem of Algebra**
# instead of ##

2023-12-23 09:25 UTC, sonntuet1997 commented on articles/why-and-how-zk-snark-works/3.Non_Interactive_Zero-Knowledge_of_a_Polynomial.md
> +Example, We have :
Malfunction math

2023-12-24 01:50 UTC, ktokto313 commented on articles/why-and-how-zk-snark-works/3.Non_Interactive_Zero-Knowledge_of_a_Polynomial.md
> +Here is the refined and grammar-checked version of your markdown:
You left this AI sentence in the document

2023-12-24 01:55 UTC, sonntuet1997 commented
Check file_naming convention

2023-12-24 01:56 UTC, sonntuet1997 commented
Missing attributes for the article

2023-12-24 01:58 UTC, ktokto313 commented on articles/why-and-how-zk-snark-works/4. General-Purpose Zero- Knowledge Proofs.md
> +assuming $\omega \in \left\{ 0,1 \right\}$   :
formatting error in the rich version

2023-12-24 02:05 UTC, ktokto313 commented on articles/why-and-how-zk-snark-works/3.Non_Interactive_Zero-Knowledge_of_a_Polynomial.md
> +*Verifier* checks :
Formatting error and also, can you provide more information on this? I can barely understand this part.

2023-12-24 03:35 UTC, closed without merging